org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
# 禁用 AGP 自动下载 SDK，使用本地已安装的平台与构建工具
android.builder.sdkDownload=false
# 抑制 compileSdk=35 与 AGP 8.5.2 的兼容性警告
android.suppressUnsupportedCompileSdk=35
# 临时：用 build-tools 自带的 aapt2 替换 Maven 分发的 aapt2（后者在本机 crunch PNG 失败）
android.aapt2FromMavenOverride=C\:/Users/15174/AppData/Local/Android/Sdk/build-tools/34.0.0/aapt2.exe
